Repository fack2/emarket, pull requests merged in 2019-09, with the labels that each got.

#47 created shop component frontend and backend
  client/package.json
  client/public/index.html
  client/src/components/App/App.js
  client/src/components/Category/index.js
  client/src/components/Category/style.css
  client/src/components/Home/index.js
  client/src/components/Navbar/index.js
  client/src/components/Product_card/index.js
  client/src/components/Product_card/style.css
  client/src/components/Search_bar/index.js
  client/src/components/Search_bar/style.css
  client/src/components/Shop/index.js
  client/src/components/Shop/style.css
  client/src/index.js
  package.json
  src/app.js
  src/controller/getProducts.js
  src/controller/get_category_products.js
  src/controller/index.js
  src/database/db_build.sql
  src/database/db_connection.js
  src/database/queries/getAllProduct.js
  src/database/queries/get_category_products.js
Labels: awaiting-review

#56 launching the searchBar configraing and handling comments
  .vscode/settings.json
  client/src/components/App/App.js
  client/src/components/Navbar/index.js
  client/src/components/Product_card/index.js
  client/src/components/Search_bar/index.js
  client/src/components/Search_bar/style.css
  client/src/components/Shop/index.js
  src/controller/get_products_by_name.js
  src/controller/index.js
  src/database/queries/get_searched_product.js
  src/server.js
Labels: done

#51 Shipping info
  client/package.json
  client/src/components/App/App.js
  client/src/components/shipping_info/index.js
  client/src/components/shipping_info/style.css
  src/controller/add_order.js
  src/controller/getProducts.js
  src/controller/index.js
  src/database/db_connection.js
  src/database/queries/getAllProduct.js
  src/database/queries/post_order.js
Labels: done

#58 Add to cart back
  client/src/components/Product_card/index.js
  client/src/components/Product_page/Add_quantity_cart/index.js
  client/src/components/Product_page/index.js
  client/src/components/Shop/index.js
  src/controller/add_to_cart.js
Labels: done

#64 Register
  client/src/components/Product_page/Add_quantity_cart/index.js
  client/src/components/register/index.js
  src/controller/index.js
  src/controller/register.js
Labels: awaiting-review, done
